# Generated by Django 6.0.3 on 2026-04-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brand_emblem_alter_car_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='brand_id',
            new_name='brand',
        ),
    ]
