# Generated by Django 6.0.3 on 2026-04-26 07:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_brand_id_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'avi'])]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
