# Generated by Django 6.0.3 on 2026-05-03 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('joined_year', models.PositiveSmallIntegerField()),
                ('mild', models.CharField(choices=[('mild_a', 'Miloddan Avvalgi'), ('mild', 'Milodiy')], default='mild')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='carmark',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmarks', to='main.car'),
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ManyToManyField(related_name='cars', to='main.dealer'),
        ),
        migrations.AddField(
            model_name='car',
            name='manufacturer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.manufacturer'),
        ),
    ]
