# Generated by Django 6.0.3 on 2026-05-03 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_dealer_manufacturer_alter_carmark_car_car_dealer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='m_name',
        ),
    ]
